estate/urls.py
'''Handles the Wesite routing'''


from django.urls import path
from . import views


urlpatterns = [
    path('', views.welcome_page, name="welcome-page"),
    path('rent_prop', views.rent_property, name="rent-prop"),
    path('user_profile', views.user_profile, name="user-profile"),
    path('sell_property', views.sell_property, name="sell-property"),
    path('lease_property', views.lease_property, name="lease-property"),
    path('buy_property', views.buy_property, name="buy-property"),
    path('search_property', views.search_property, name="search-property"),
    path('update_property/<property_id>', views.update_property_rent, name="update-property"),
    path('update_property_s/<property_id>', views.update_property_sale, name="update-property-s"),
    path('my_listings', views.listed_properties, name="my-listings"),
    path('view-property_s/<property_id>', views.view_property_on_sale, name="view-property-s"),
    path('view-property_r/<property_id>', views.view_property_on_lease, name="view-property-r"),
    path('delete-property_r/<property_id>', views.delete_property_on_lease, name="delete-property-r"),
    path('delete-property_s/<property_id>', views.delete_property_on_sale, name="delete-property-s"),
    path('update-profile/<user_id>', views.update_profile, name="update-profile"),
    path('whilist_rent/<property_id>', views.toggle_wishlist_rent, name="toggle-wishlist-rent"),
    path('whilist_buy/<property_id>', views.toggle_wishlist_buy, name="toggle-wishlist-buy"),
    path('whilist', views.wishlist, name="wishlist"),
    path('edit_password', views.change_password, name="change-password"),
    path('edit_password_success', views.change_password_success, name="password-success"),
    path('settings', views.settings, name="settings"),
    path('delete_account', views.delete_account, name="delete-account"),
    path('best_deals_rent', views.best_deals_on_lease, name="best-deals-rent"),
    path('best_deals_sale', views.best_deals_on_sale, name="best-deals-sale"),
]

estate_web/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static 
from django.conf import settings 


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('estate.urls')),
    path('members/', include('django.contrib.auth.urls')),
    path('members/', include('members.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


admin.site.site_title="Admin Page" #The browsers title
admin.site.site_header="My Club Administration Page"
admin.site.index_title= "Welcome To THe admin Area......"

urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static 
from django.conf import settings 


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('estate.urls')),
    path('members/', include('django.contrib.auth.urls')),
    path('members/', include('members.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


admin.site.site_title="Admin Page" #The browsers title
admin.site.site_header="My Club Administration Page"
admin.site.index_title= "Welcome To THe admin Area......"

estate/models.py
'''Models holding/Handling all our datatbases requirement used all through the website'''

from django.db import models
from datetime import datetime
from .choices import STATES


#model handling the datatabase requirements cointaining all the property up for sale requirements
class PropertyManagementSale(models.Model):
    user_id=models.IntegerField('Landlord', blank=False, default=1)
    summary=models.CharField('Short building tag', max_length=30, default=None)
    property_description = models.TextField('Description')
    location = models.CharField('Location', max_length=255)
    state= models.CharField(max_length=20,choices=STATES, default='Lagos')
    phone_number = models.IntegerField('Phone Number')
    owner = models.CharField('Listed By', max_length=120)
    price = models.DecimalField(max_digits=12, decimal_places=2, null=True, blank=True)
    bedrooms = models.IntegerField(default=0, blank=True, null=True)
    bathrooms = models.IntegerField(default=0, blank=True, null=True)
    available= models.BooleanField('Available', default=True)
    last_updated = models.DateTimeField(auto_now=True)#To pull out the last time the particular model was actually updated 
    whilist=models.BooleanField('Add to Whilist', default=False)
    base_image= models.ImageField(null=True, blank=True, upload_to="images/buy")
    image1= models.ImageField(null=True, blank=True, upload_to="images/buy")
    image2= models.ImageField(null=True, blank=True, upload_to="images/buy")
    image3= models.ImageField(null=True, blank=True, upload_to="images/buy")
    image4= models.ImageField(null=True, blank=True, upload_to="images/buy")
    image5= models.ImageField(null=True, blank=True, upload_to="images/buy")
    image6= models.ImageField(null=True, blank=True, upload_to="images/buy")
    listed_date=models.DateTimeField(default=datetime.now, blank=True)
    
    class NegotiateChoices(models.TextChoices):
        YES = 'Y', 'Yes'
        NO = 'N', 'No'

    negotiate = models.CharField(max_length=1, choices=NegotiateChoices.choices, default=NegotiateChoices.NO, blank=True, null=True)

    def __str__(self):
        return self.summary




#model handling the datatabase requirements cointaining all the property up for lease requirements
class PropertyManagementRent(models.Model):
    user_id=models.IntegerField('Landlord', blank=False, default=1)
    owner = models.CharField('Listed By', max_length=120, default="Akinfiresoye")
    summary=models.CharField('Short building tag', max_length=30, default=None)
    description= models.TextField('Description')
    location= models.CharField('Location', max_length=255)
    state= models.CharField(max_length=20,choices=STATES, default='Lagos State')
    phone_number = models.IntegerField('Phone Number')
    price_range = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    available=models.BooleanField('Availble', default=True)
    bedrooms = models.IntegerField(default=1, blank=True, null=True)
    bathrooms = models.IntegerField(default=1, blank=True, null=True)
    last_updated = models.DateTimeField(auto_now=True)
    whilist=models.BooleanField('Add to Whilist', default=False)
    base_image= models.ImageField(null=True, blank=True, upload_to="images/rent")
    image1= models.ImageField(null=True, blank=True, upload_to="images/rent")
    image2= models.ImageField(null=True, blank=True, upload_to="images/rent")
    image3= models.ImageField(null=True, blank=True, upload_to="images/rent")
    image4= models.ImageField(null=True, blank=True, upload_to="images/rent")
    image5= models.ImageField(null=True, blank=True, upload_to="images/rent")
    image6= models.ImageField(null=True, blank=True, upload_to="images/rent")
    listed_date=models.DateTimeField(default=datetime.now, blank=True)
    def __str__(self):
        return self.summary

estate/views.py
'''Handles Main Functionality of the Website'''

from django.shortcuts import render, redirect, get_object_or_404
from .models import PropertyManagementSale, PropertyManagementRent
from .forms import LeaseForm, SellForm
from django.http import HttpResponseRedirect
from django.contrib import messages
from members.forms import UpdateUserForm
from django.contrib.auth.models import User
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth import update_session_auth_hash




#Basic Welcome page for users/guests
def welcome_page(request):
    if request.user.is_authenticated:
        messages.success(request, 'Welcome Back')
        return redirect('user-profile')
    else:
        return render(request, 'estate/welcome_page.html')



'''Property Management Function'''
#Function/View which manages the uploading of properties for sale
def sell_property(request):
    if request.user.is_authenticated:
        submitted= False
        #if the form is submitted do 👇
        if request.method== 'POST':
            form=SellForm(request.POST, request.FILES) #request.FILES helps deals with the picture management
            if form.is_valid():
                landlord= form.save(commit=False)
                landlord.user_id= request.user.id
                form.save()
                return HttpResponseRedirect('/sell_property?submitted=True')#setting the form to true so we dont submit the form twice
        #else just display the form and input required data
        else:
            form= SellForm
            if 'submitted' in request.GET:
                submitted=True
        return render(request, 'estate/sell_property.html', {'form': form, 'submitted':submitted})
    else:
        messages.success(request, ('You need to be logged in to accesss this page'))
        return redirect('welcome-page')


#Function/View that manages the uploading of properties for Rent
def lease_property(request):
    if request.user.is_authenticated:
        submitted= False
        if request.method== 'POST':
            form=LeaseForm(request.POST, request.FILES) #request.FILES to handle the images 
            if form.is_valid():
                landlord= form.save(commit=False)
                landlord.user_id= request.user.id
                form.save()
                return HttpResponseRedirect('/lease_property?submitted=True')
        else:
            form= LeaseForm
            if 'submitted' in request.GET:
                submitted=True
        return render(request, 'estate/lease_property.html', {'form': form, 'submitted':submitted})
    else:
        messages.success(request, ('You need to be logged in to accesss this page'))
        return redirect('welcome-page')


#Function/View that queries and brings out all the property being leased
def rent_property(request):
    if request.user.is_authenticated:
        #The line that does the actual querying and its organized by the date listed
        leased_property_list= PropertyManagementRent.objects.order_by('-listed_date').all()
        return render(request, 'estate/rent_property.html', {'leased': leased_property_list})
    else:
        messages.success(request, ('You need to be logged in to accesss this page'))
        return redirect('welcome-page')


#Function/View that queries and brings out all the property on sale
def buy_property(request):
    if request.user.is_authenticated:
        #The line that does the actual querying and its organized by the date listed from the latest to the oldest 
        propery_sale_list=PropertyManagementSale.objects.order_by('-listed_date').all()
        return render(request, 'estate/buy_property.html', {'buy': propery_sale_list})
    else:
        messages.success(request, ('You need to be logged in to accesss this page'))
        return redirect('welcome-page')


#View/Function that handles the updating of property already available for rent
def update_property_rent(request, property_id):
    if request.user.is_authenticated:
        #gets the particular listing that needs to be updated using their id
        property=PropertyManagementRent.objects.get(pk= property_id)
        #instance=property then fills the form based on previous data
        form= LeaseForm(request.POST or None,request.FILES or None, instance=property)
        if form.is_valid():
            form.save()
            messages.success(request, "Property Updated Successfully")
            return redirect('my-listings')
        return render(request, 'estate/update_property.html', {'property': property, 'form': form})
    else:
        messages.success(request, ('You need to be logged in to accesss this page'))
        return redirect('welcome-page')


#View/Function that handles the updating of property already available for sale
def update_property_sale(request, property_id):
    if request.user.is_authenticated:
        #gets the particular listing that needs to be updated using their id
        property=PropertyManagementSale.objects.get(pk= property_id)
        #instance=property then fills the form based on previous data
        form= SellForm(request.POST or None, request.FILES or None, instance=property)
        if form.is_valid():
            form.save()
            messages.success(request, "Property Updated Successfully")
            return redirect('my-listings')
        return render(request, 'estate/update_property_s.html', {'property': property, 'form': form})
    else:
        messages.success(request, ('You need to be logged in to accesss this page'))
        return redirect('welcome-page')


#View/Function that deletes unwanted lisings from a users listings
def delete_property_on_lease(request, property_id):
    if request.user.is_authenticated:
        #getting the property_id which will be used to handle the deletion
        property1= PropertyManagementRent.objects.get(pk=property_id)
        #keeps another user from deleting a users data 
        if request.user.id == property1.user_id:
            #what does the actual deleting based on the property_id
            property1.delete()
            messages.success(request, ("Property deleted successfully"))
            return redirect('my-listings')
        else:
            messages.error(request, ('You Arent authorized to delete this property'))
            return redirect('my-listings')
    else:
        messages.success(request, ('You need to be logged in to accesss this page'))
        return redirect('welcome-page')


#View/Function that deletes a property on sale using the property id
def delete_property_on_sale(request, property_id):
    if request.user.is_authenticated:
        property1= PropertyManagementSale.objects.get(pk=property_id)
        #Additional layer of security
        if request.user.id == property1.user_id:
            property1.delete()
            messages.success(request, ("Property deleted successfully"))
            return redirect('my-listings')
        else:
            messages.success(request, ('You Arent authorized to delete this property'))
            return redirect('my-listings')
    else:
        messages.success(request, ('You need to be logged in to accesss this page'))
        return redirect('welcome-page')


#Views/Functions that pulls out all details of a property on sale
def view_property_on_sale(request, property_id):
    if request.user.is_authenticated:
        #actual line that does the heavy lifting
        property= PropertyManagementSale.objects.get(pk=property_id)
        return render(request, 'estate/view_property_s.html', {'property':property})
    else:
        messages.success(request, ('You need to be logged in to accesss this page'))
        return redirect('welcome-page')


#Views/Functions that pulls out all details of a property on lease
def view_property_on_lease(request, property_id):
    if request.user.is_authenticated:
        #actual line that does the heavy lifting
        property= PropertyManagementRent.objects.get(pk=property_id)
        return render(request, 'estate/view_property_r.html', {'property':property})
    else:
        messages.success(request, ('You need to be logged in to accesss this page'))
        return redirect('welcome-page')


#View/Function that queries the datatbase containing the properties on lease and ordering them from the lowest price to the highest price
def best_deals_on_lease(request):
    if request.user.is_authenticated:
        property_on_lease= PropertyManagementRent.objects.order_by('price_range').all()
        return render(request, 'estate/best_deals_r.html', {'property': property_on_lease})
    else:
        return redirect('welcome-page')


#View/Function that queries the datatbase containing the properties on sale and ordering them from the lowest price to the highest price
def best_deals_on_sale(request):
    if request.user.is_authenticated:
        property_on_sale= PropertyManagementSale.objects.order_by('price').all()
        return render(request, 'estate/best_deals_s.html', {'property': property_on_sale})
    else:
        return redirect('welcome-page')




'''User Experience Views'''
#view handling the users profile settings
def user_profile(request):
    if request.user.is_authenticated:
        return render(request, 'estate/user_profile.html', {})
    else:
        messages.success(request, ('You need to be logged in to accesss this page'))
        return redirect('welcome-page')


#View That shows Properties the users listed 
def listed_properties(request):
    if request.user.is_authenticated:
        model1= request.user.id
        model2= request.user.id
        #filtering the listings using both the users id and the properties id 
        property1= PropertyManagementRent.objects.filter(user_id=model1)
        property2= PropertyManagementSale.objects.filter(user_id=model2)
        return render(request, 'estate/my_listings.html', {'property1':property1, 'property2':property2})
    else:

estate/templates/estate/base.html
<!doctype html>
<html lang="en">
{% load static %}
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Estate Web</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">


    {% block extra_css %}{% endblock %}  <!-- ✅ This enables custom CSS per page -->
  </head>
  <body>
    {% include 'estate/navbar.html' %}
    <br/>
    <div class="container mt-5">
        {% if messages %}
            {% for message in messages %}
              <div class="alert alert-success fade show" role="alert">
                {{ message }}
              </div>
            {% endfor %}
        {% endif %}
        {% block content %}
        {% endblock %}
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>

  </body>
</html>

estate/templates/estate/buy_property.html
{% extends 'estate/base.html' %}
{% load static%}


{% block extra_css %}
  <link rel="stylesheet" href="{% static 'estate/css/buy.css' %}">
{% endblock %}

{% block content %}


<br/>

<div class="container">
  <div class="text-center mb-4">
    <h1 class="display-4 text-primary">On Sale</h1>
    <hr class="hr-custom">
  </div>

  <div class="row">
    {% for bought in buy %}
      {% if bought.available %}
        <div class="col-md-6 col-lg-4 mb-4">
          <div class="card shadow h-100 d-flex flex-column">
            <div class="card-body d-flex flex-column position-relative">

              <a href="{% url 'toggle-wishlist-buy' bought.id %}"
                 class="position-absolute top-0 end-0 m-2"
                 style="z-index: 1; font-size: 1.5rem; color: var(--blue);">
                {% if bought.whilist %}
                  <i class="fas fa-bookmark"></i>
                {% else %}
                  <i class="far fa-bookmark"></i>
                {% endif %}
              </a>

              <h5 class="card-title fw-semibold text-primary">{{ bought.summary }}</h5>
              <h6 class="text-muted">Location: {{ bought.location }}</h6>
              <h6 class="text-muted">State: {{ bought.state }}</h6>
              <hr>
              <ul class="list-unstyled small text-muted">
                <li><strong>Description:</strong> {{ bought.property_description }}</li>
                <li><strong>Price:</strong> ₦{{ bought.price }}</li>
                <li><strong>Phone Number:</strong> {{ bought.phone_number }}</li>
                <li><strong>Negotiable:</strong> {{ bought.get_negotiate_display }}</li>
                <li><strong>Date Listed:</strong> {{ bought.listed_date|date:"M d, Y" }}</li>
              </ul>
              <div class="mt-auto text-center">
                <a href="{% url 'view-property-s' property_id=bought.id %}" class="btn btn-outline-primary">
                  View Property
                </a>
              </div>
            </div>
          </div>
        </div>
      {% endif %}
    {% endfor %}
  </div>
</div>
{% endblock %}

estate/templates/estate/change_passw.html
{% extends 'estate/base.html' %}

{% load static%}


{% block extra_css %}
  <link rel="stylesheet" href="{% static 'estate/css/change_passw.css' %}">
{% endblock %}



{% block content %}


<div class="container">
  <div class="row justify-content-center">
    <div class="col-lg-6 col-md-8">
      <div class="card mt-5 shadow">
        <div class="card-header text-center py-4">
          <h3 class="mb-0 text-success">
            <i class="fas fa-key me-2"></i>{{ title }}
          </h3>
        </div>
        <div class="card-body p-5">
          {% if messages %}
            {% for message in messages %}
              <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
                {{ message }}
                <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
              </div>
            {% endfor %}
          {% endif %}

          {% if form.non_field_errors %}
            <div class="alert alert-danger">
              {% for error in form.non_field_errors %}
                <p class="mb-0">{{ error }}</p>
              {% endfor %}
            </div>
          {% endif %}

          <form method="post">
            {% csrf_token %}

            <div class="mb-4">
              <label for="{{ form.old_password.id_for_label }}" class="form-label fw-bold">
                Current Password
              </label>
              {{ form.old_password }}
              {% if form.old_password.errors %}
                <div class="text-danger mt-1">
                  {% for error in form.old_password.errors %}
                    <small>{{ error }}</small>
                  {% endfor %}
                </div>
              {% endif %}
            </div>

            <div class="mb-4">
              <label for="{{ form.new_password1.id_for_label }}" class="form-label fw-bold">
                New Password
              </label>
              {{ form.new_password1 }}
              {% if form.new_password1.errors %}
                <div class="text-danger mt-1">
                  {% for error in form.new_password1.errors %}
                    <small>{{ error }}</small>
                  {% endfor %}
                </div>
              {% endif %}
              <div class="form-text">
                <small>
                  <ul class="mb-0 ps-3">
                    <li>Your password can't be too similar to your other personal information.</li>
                    <li>It must contain at least 8 characters.</li>
                    <li>It can't be a commonly used password.</li>
                    <li>It can't be entirely numeric.</li>
                  </ul>
                </small>
              </div>
            </div>

            <div class="mb-4">
              <label for="{{ form.new_password2.id_for_label }}" class="form-label fw-bold">
                Confirm New Password
              </label>
              {{ form.new_password2 }}
              {% if form.new_password2.errors %}
                <div class="text-danger mt-1">
                  {% for error in form.new_password2.errors %}
                    <small>{{ error }}</small>
                  {% endfor %}
                </div>
              {% endif %}
            </div>

            <div class="d-grid gap-2">
              <button type="submit" class="btn btn-success btn-lg">
                <i class="fas fa-save me-2"></i>Change Password
              </button>
              <a href="{% url 'user-profile' %}" class="btn btn-outline-secondary">
                <i class="fas fa-arrow-left me-2"></i>Back to Dashboard
              </a>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

estate/templates/estate/my_listings.html
{% extends 'estate/base.html' %}

{% block content %}
{% if user.is_authenticated %}
<br/>

<div class="container">
  <div class="text-center mb-4">
    <h1 class="display-4" style="color: var(--bs-success, #198754);">My Listings</h1>
    <hr class="w-25 mx-auto" style="border-top: 2px solid var(--bs-success, #198754);">
  </div>

  <!-- Lease Listings -->
  <div class="row">
    {% for property in property1 %}
      {% if property %}
        <div class="col-md-6 col-lg-4 mb-4">
          <div class="card border-0 shadow h-100 d-flex flex-column" style="background-color: var(--bs-light, #f8f9fa);">
            <div class="card-body d-flex flex-column position-relative">
              <span class="badge text-bg-success position-absolute top-0 end-0 m-2">On Lease</span>
              <h5 class="card-title fw-semibold" style="color: var(--bs-success, #198754);">{{ property.summary }}</h5>
              <h6 class="text-muted">Location: {{ property.location }}</h6>
              <hr>
              <ul class="list-unstyled small text-secondary">
                <li><strong>Description:</strong> {{ property.description }}</li>
                <li><strong>Price Range:</strong> ₦{{ property.price_range }}</li>
                <li><strong>Phone Number:</strong> {{ property.phone_number }}</li>
              </ul>
              <div class="mt-auto d-flex justify-content-between">
                <a href="{% url 'update-property' property_id=property.id %}" class="btn btn-outline-success btn-sm">Update</a>
                <a href="{% url 'delete-property-r' property_id=property.id %}" class="btn btn-outline-danger btn-sm">Delete</a>
              </div>
            </div>
          </div>
        </div>
      {% endif %}
    {% endfor %}
  </div>

  <!-- Sale Listings -->
  <div class="row mt-4">
    {% for property in property2 %}
      {% if property %}
        <div class="col-md-6 col-lg-4 mb-4">
          <div class="card border-0 shadow h-100 d-flex flex-column" style="background-color: var(--bs-light, #f8f9fa);">
            <div class="card-body d-flex flex-column position-relative">
              <span class="badge text-bg-primary position-absolute top-0 end-0 m-2">On Sale</span>
              <h5 class="card-title fw-semibold" style="color: var(--bs-primary, #0d6efd);">{{ property.summary }}</h5>
              <h6 class="text-muted">Location: {{ property.location }}</h6>
              <hr>
              <ul class="list-unstyled small text-secondary">
                <li><strong>Description:</strong> {{ property.property_description }}</li>
                <li><strong>Price:</strong> ₦{{ property.price }}</li>
                <li><strong>Phone Number:</strong> {{ property.phone_number }}</li>
                <li><strong>Negotiable:</strong> {{ property.get_negotiate_display }}</li>
              </ul>
              <div class="mt-auto d-flex justify-content-between">
                <a href="{% url 'update-property-s' property_id=property.id %}" class="btn btn-outline-primary btn-sm">Update</a>
                <a href="{% url 'delete-property-s' property_id=property.id %}" class="btn btn-outline-danger btn-sm">Delete</a>
              </div>
            </div>
          </div>
        </div>
      {% endif %}
    {% endfor %}
  </div>

  {% if not property1 and not property2 %}
  <center>
      <a href="{% url 'user-profile' %}" class="btn btn-outline-secondary">
        <i class="fas fa-arrow-left me-2"></i>Back to Dashboard
      </a>
    </center>
    <div class="alert alert-warning text-center mt-4" role="alert">
      You don't have any listings yet.
    </div>
  {% endif %}
</div>
{% endif %}
{% endblock %}

estate/templates/estate/search.html
{% extends 'estate/base.html' %}

{% block content %}
{% if searched %}
<div class="container mt-5">
  <div class="text-center mb-5">
    <h1 class="display-4 text-success animate__animated animate__fadeInDown">Search Results for "<span class="text-primary">{{ searched }}</span>"</h1>
    <hr class="w-50 mx-auto border-success border-3 opacity-75">
  </div>

  {# --- For Rent Properties --- #}
  {% if properties %}
  <h2 class="text-success mb-4 animate__animated animate__fadeInLeft">Properties for Rent</h2>
  <div class="row row-cols-1 row-cols-md-2 row-cols-lg-3 g-4 mb-5">
    {% for property in properties %}
      {% if property.available %}
        <div class="col animate__animated animate__fadeInUp">
          <div class="card h-100 shadow-lg border-success rounded-3 overflow-hidden">
            <div class="card-body d-flex flex-column p-4">
              <h5 class="card-title text-success mb-2">{{ property.summary }}</h5>
              <h6 class="card-subtitle mb-3 text-muted">Location: {{ property.location }}</h6>
              <p class="card-text flex-grow-1">{{ property.description|truncatechars:100 }}</p>
              <ul class="list-unstyled mb-3">
                <li><strong>Price Range:</strong> <span class="text-success">₦{{ property.price_range }}</span></li>
                <li><strong>Phone:</strong> {{ property.phone_number }}</li>
              </ul>
              <div class="mt-auto text-center">
                <a href="{% url 'view-property-r' property.id %}" class="btn btn-success btn-lg px-4 rounded-pill">View Details</a>
              </div>
            </div>
          </div>
        </div>
      {% endif %}
    {% endfor %}
  </div>
  {% else %}
  <div class="alert alert-info text-center animate__animated animate__fadeIn" role="alert">
    No properties found for rent matching your search.
  </div>
  {% endif %}

  ---
  <div class="my-5"></div> {# Adds some space between sections #}
  ---

  {# --- For Sale Properties --- #}
  {% if properties1 %}
  <h2 class="text-primary mb-4 animate__animated animate__fadeInRight">Properties for Sale</h2>
  <div class="row row-cols-1 row-cols-md-2 row-cols-lg-3 g-4">
    {% for property_sale in properties1 %} {# Renamed variable for clarity #}
      {% if property_sale.available %}
        <div class="col animate__animated animate__fadeInUp">
          <div class="card h-100 shadow-lg border-primary rounded-3 overflow-hidden">
            <div class="card-body d-flex flex-column p-4">
              <h5 class="card-title text-primary mb-2">{{ property_sale.summary }}</h5>
              <h6 class="card-subtitle mb-3 text-muted">Location: {{ property_sale.location }}</h6>
              <p class="card-text flex-grow-1">{{ property_sale.property_description|truncatechars:100 }}</p>
              <ul class="list-unstyled mb-3">
                <li><strong>Price:</strong> <span class="text-primary">₦{{ property_sale.price }}</span></li>
                <li><strong>Phone:</strong> {{ property_sale.phone_number }}</li>
                <li><strong>Negotiable:</strong> {{ property_sale.get_negotiate_display }}</li>
              </ul>
              <div class="mt-auto text-center">
                <a href="{% url 'view-property-s' property_sale.id %}" class="btn btn-primary btn-lg px-4 rounded-pill">View Details</a>
              </div>
            </div>
          </div>
        </div>
      {% endif %}
    {% endfor %}
  </div>
  {% else %}
  <div class="alert alert-info text-center mt-4 animate__animated animate__fadeIn" role="alert">
    No properties found for sale matching your search.
  </div>
  {% endif %}

</div>

{% else %}
<div class="container mt-5 text-center">
  <div class="alert alert-warning animate__animated animate__bounceIn" role="alert">
    <h4 class="alert-heading">Oops!</h4>
    <p>It looks like you haven't searched for anything yet. Please use the search bar to find properties.</p>
    <hr>
    <p class="mb-0">Start by typing what you're looking for, like "apartment" or "Lagos."</p>
  </div>
</div>
{% endif %}
{% endblock %}